version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "NUnit"
      - dependency-name: "NUnit3TestAdapter"
      - dependency-name: "SonarAnalyzer.CSharp"
      - dependency-name: "morelinq"
      - dependency-name: "Microsoft.NET.Test.Sdk"
